# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
baslayanSalonlar=[]
girisYapan2=0
class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.resize(555, 812)
        self.centralwidget = QtWidgets.QWidget(Test)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 10, 521, 741))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 400, 421, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.radioButton_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_3.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_3.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_3.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_3.addWidget(self.radioButton_12)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_19.addWidget(self.label_5)
        self.radioButton_17 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_17.setObjectName("radioButton_17")
        self.horizontalLayout_19.addWidget(self.radioButton_17)
        self.radioButton_18 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_18.setObjectName("radioButton_18")
        self.horizontalLayout_19.addWidget(self.radioButton_18)
        self.radioButton_19 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_19.setObjectName("radioButton_19")
        self.horizontalLayout_19.addWidget(self.radioButton_19)
        self.radioButton_20 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_20.setObjectName("radioButton_20")
        self.horizontalLayout_19.addWidget(self.radioButton_20)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_18.addWidget(self.label_4)
        self.radioButton_13 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_18.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_18.addWidget(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_18.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_16.setObjectName("radioButton_16")
        self.horizontalLayout_18.addWidget(self.radioButton_16)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_2.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_2.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_2.addWidget(self.radioButton_8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_20.addWidget(self.label_6)
        self.radioButton_21 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_21.setObjectName("radioButton_21")
        self.horizontalLayout_20.addWidget(self.radioButton_21)
        self.radioButton_22 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_22.setObjectName("radioButton_22")
        self.horizontalLayout_20.addWidget(self.radioButton_22)
        self.radioButton_23 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_23.setObjectName("radioButton_23")
        self.horizontalLayout_20.addWidget(self.radioButton_23)
        self.radioButton_24 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_24.setObjectName("radioButton_24")
        self.horizontalLayout_20.addWidget(self.radioButton_24)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(0, 30, 581, 361))
        self.listView.setObjectName("listView")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(90, 220, 201, 121))
        self.label_17.setObjectName("label_17")
        Test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 23))
        self.menubar.setObjectName("menubar")
        Test.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Test)
        self.statusbar.setObjectName("statusbar")
        Test.setStatusBar(self.statusbar)

        vt = sqlite3.connect('ogrenci.db')
        im = vt.cursor()
        im.execute("""SELECT * FROM baslayan""")
        for i in im:
            im2=vt.cursor()
            im2.execute("""SELECT * FROM salon""")
            for j in im2:
                if(str(i[1])==str(j[5]) and str(i[2])==str(j[6])):
                    baslayanSalonlar.append(j[0])
        im4=vt.cursor()
        im4.execute("""SELECT * FROM girisYapan""")
        for i in im4: 
           self.girisYapan2=str(i[1])
        im3=vt.cursor()
        im3.execute("""SELECT * from oYerles WHERE ogrenciId='"""+str(girisYapan2)+"""'""")
        for j in im3:
            for a in range(0,len(self.baslayanSalonlar)):
                if(j[2]==baslayanSalonlar[a]):
                    self.groupBox.setVisible(True)
        vt.close()        
        
        self.retranslateUi(Test)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "MainWindow"))
        self.label.setText(_translate("Test", "Cevap1"))
        self.radioButton.setText(_translate("Test", "A"))
        self.radioButton_2.setText(_translate("Test", "B"))
        self.radioButton_3.setText(_translate("Test", "C"))
        self.radioButton_4.setText(_translate("Test", "D"))
        self.label_3.setText(_translate("Test", "Cevap2"))
        self.radioButton_9.setText(_translate("Test", "A"))
        self.radioButton_10.setText(_translate("Test", "B"))
        self.radioButton_11.setText(_translate("Test", "C"))
        self.radioButton_12.setText(_translate("Test", "D"))
        self.label_5.setText(_translate("Test", "Cevap3"))
        self.radioButton_17.setText(_translate("Test", "A"))
        self.radioButton_18.setText(_translate("Test", "B"))
        self.radioButton_19.setText(_translate("Test", "C"))
        self.radioButton_20.setText(_translate("Test", "D"))
        self.label_4.setText(_translate("Test", "Cevap4"))
        self.radioButton_13.setText(_translate("Test", "A"))
        self.radioButton_14.setText(_translate("Test", "B"))
        self.radioButton_15.setText(_translate("Test", "C"))
        self.radioButton_16.setText(_translate("Test", "D"))
        self.label_2.setText(_translate("Test", "Cevap5"))
        self.radioButton_5.setText(_translate("Test", "A"))
        self.radioButton_6.setText(_translate("Test", "B"))
        self.radioButton_7.setText(_translate("Test", "C"))
        self.radioButton_8.setText(_translate("Test", "D"))
        self.label_6.setText(_translate("Test", "Cevap6"))
        self.radioButton_21.setText(_translate("Test", "A"))
        self.radioButton_22.setText(_translate("Test", "B"))
        self.radioButton_23.setText(_translate("Test", "C"))
        self.radioButton_24.setText(_translate("Test", "D"))
        self.label_17.setText(_translate("Test", "Şuanda Sınav Yok"))
        self.groupBox.setVisible(True)
        self.label_17.setVisible(False)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Test = QtWidgets.QMainWindow()
    ui = Ui_Test()
    ui.setupUi(Test)
    Test.show()
    sys.exit(app.exec_())

